// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Main Character":return img`
................................
................................
................................
................................
................................
................................
............444444..............
...........44444444.............
..........4444444444............
...........fd17dd4444...........
...........fd17dd7444...........
...........fddddddd4............
...........fdddddddf............
...........fdddddddf............
............fffffff.............
................................
...........fffffffff............
..........fffff6fffff...........
.........ffffff6ffffff..........
.........fffbff6ffbfff..........
.........ffbfff6fffbff..........
.........ffbfff6fffbff..........
.........ffbfff6fffbff..........
.........ffbfff6fffbff..........
.........dddfff6fffddd..........
...........ffff6ffff............
...........fffffffff............
...........fffffffff............
...........ffffbffff............
...........ffffbffff............
...........ffffbffff............
...........ffffbffff............
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
