// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Main Character":return img`
................................
................................
................................
................................
................................
............bbbbbb..............
...........b444444b.............
..........b44444444b............
.........b4444444444b...........
..........bfd17dd4444b..........
..........bfd17dd7444b..........
..........bfddddddd4b...........
..........bfdddddddfb...........
..........bfdddddddfb...........
...........bfffffffb............
...........bbbbbbbbb............
..........bfffffffffb...........
.........bfffff6fffffb..........
........bffffff6ffffffb.........
........bfffbff6ffbfffb.........
........bffbfff6fffbffb.........
........bffbfff6fffbffb.........
........bffbfff6fffbffb.........
........bffbfff6fffbffb.........
........bdddfff6fffdddb.........
........bbbffff6ffffbbb.........
..........bfffffffffb...........
..........bfffffffffb...........
..........bffffbffffb...........
..........bffffbffffb...........
..........bffffbffffb...........
..........bffffbffffb...........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
